apiVersion: v1
kind: ConfigMap
metadata:
  name: config2
data:
  FOO_ENV: bar
  HELLO_ENV: world
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - configMapRef:
         name: config2